# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='todo.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntodo.proto\x12\x08protobuf\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"B\n\x04ToDo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0f\n\x07is_done\x18\x04 \x01(\x08\"\x19\n\x0bToDoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xdc\x03\n\x0bTodoService\x12\x32\n\x07\x41\x64\x64User\x12\x0e.protobuf.User\x1a\x15.protobuf.UserRequest\"\x00\x12<\n\nDeleteUser\x12\x15.protobuf.UserRequest\x1a\x15.protobuf.UserRequest\"\x00\x12\x32\n\x07\x41\x64\x64Todo\x12\x0e.protobuf.ToDo\x1a\x15.protobuf.ToDoRequest\"\x00\x12\x32\n\x07GetToDo\x12\x15.protobuf.ToDoRequest\x1a\x0e.protobuf.ToDo\"\x00\x12=\n\x0bSetDoneToDo\x12\x15.protobuf.ToDoRequest\x1a\x15.protobuf.ToDoRequest\"\x00\x12<\n\nDeleteToDo\x12\x15.protobuf.ToDoRequest\x1a\x15.protobuf.ToDoRequest\"\x00\x12\x35\n\x08GetToDos\x12\x15.protobuf.UserRequest\x1a\x0e.protobuf.ToDo\"\x00\x30\x01\x12?\n\x0b\x44\x65leteToDos\x12\x15.protobuf.UserRequest\x1a\x15.protobuf.ToDoRequest\"\x00\x30\x01\x62\x06proto3')
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='protobuf.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.User.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuf.User.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=56,
)


_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='protobuf.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.UserRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=83,
)


_TODO = _descriptor.Descriptor(
  name='ToDo',
  full_name='protobuf.ToDo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.ToDo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='protobuf.ToDo.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='protobuf.ToDo.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_done', full_name='protobuf.ToDo.is_done', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=151,
)


_TODOREQUEST = _descriptor.Descriptor(
  name='ToDoRequest',
  full_name='protobuf.ToDoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.ToDoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['ToDo'] = _TODO
DESCRIPTOR.message_types_by_name['ToDoRequest'] = _TODOREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.User)
  ))
_sym_db.RegisterMessage(User)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERREQUEST,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.UserRequest)
  ))
_sym_db.RegisterMessage(UserRequest)

ToDo = _reflection.GeneratedProtocolMessageType('ToDo', (_message.Message,), dict(
  DESCRIPTOR = _TODO,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.ToDo)
  ))
_sym_db.RegisterMessage(ToDo)

ToDoRequest = _reflection.GeneratedProtocolMessageType('ToDoRequest', (_message.Message,), dict(
  DESCRIPTOR = _TODOREQUEST,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.ToDoRequest)
  ))
_sym_db.RegisterMessage(ToDoRequest)



_TODOSERVICE = _descriptor.ServiceDescriptor(
  name='TodoService',
  full_name='protobuf.TodoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=181,
  serialized_end=657,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddUser',
    full_name='protobuf.TodoService.AddUser',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_USERREQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteUser',
    full_name='protobuf.TodoService.DeleteUser',
    index=1,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_USERREQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddTodo',
    full_name='protobuf.TodoService.AddTodo',
    index=2,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODOREQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetToDo',
    full_name='protobuf.TodoService.GetToDo',
    index=3,
    containing_service=None,
    input_type=_TODOREQUEST,
    output_type=_TODO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetDoneToDo',
    full_name='protobuf.TodoService.SetDoneToDo',
    index=4,
    containing_service=None,
    input_type=_TODOREQUEST,
    output_type=_TODOREQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteToDo',
    full_name='protobuf.TodoService.DeleteToDo',
    index=5,
    containing_service=None,
    input_type=_TODOREQUEST,
    output_type=_TODOREQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetToDos',
    full_name='protobuf.TodoService.GetToDos',
    index=6,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_TODO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteToDos',
    full_name='protobuf.TodoService.DeleteToDos',
    index=7,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_TODOREQUEST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODOSERVICE)

DESCRIPTOR.services_by_name['TodoService'] = _TODOSERVICE

# @@protoc_insertion_point(module_scope)
