# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protobuf.todo_pb2 as todo__pb2


class TodoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddUser = channel.unary_unary(
        '/protobuf.TodoService/AddUser',
        request_serializer=todo__pb2.User.SerializeToString,
        response_deserializer=todo__pb2.UserRequest.FromString,
        )
    self.DeleteUser = channel.unary_unary(
        '/protobuf.TodoService/DeleteUser',
        request_serializer=todo__pb2.UserRequest.SerializeToString,
        response_deserializer=todo__pb2.UserRequest.FromString,
        )
    self.AddTodo = channel.unary_unary(
        '/protobuf.TodoService/AddTodo',
        request_serializer=todo__pb2.ToDo.SerializeToString,
        response_deserializer=todo__pb2.ToDoRequest.FromString,
        )
    self.GetToDo = channel.unary_unary(
        '/protobuf.TodoService/GetToDo',
        request_serializer=todo__pb2.ToDoRequest.SerializeToString,
        response_deserializer=todo__pb2.ToDo.FromString,
        )
    self.SetDoneToDo = channel.unary_unary(
        '/protobuf.TodoService/SetDoneToDo',
        request_serializer=todo__pb2.ToDoRequest.SerializeToString,
        response_deserializer=todo__pb2.ToDoRequest.FromString,
        )
    self.DeleteToDo = channel.unary_unary(
        '/protobuf.TodoService/DeleteToDo',
        request_serializer=todo__pb2.ToDoRequest.SerializeToString,
        response_deserializer=todo__pb2.ToDoRequest.FromString,
        )
    self.GetToDos = channel.unary_stream(
        '/protobuf.TodoService/GetToDos',
        request_serializer=todo__pb2.UserRequest.SerializeToString,
        response_deserializer=todo__pb2.ToDo.FromString,
        )
    self.DeleteToDos = channel.unary_stream(
        '/protobuf.TodoService/DeleteToDos',
        request_serializer=todo__pb2.UserRequest.SerializeToString,
        response_deserializer=todo__pb2.ToDoRequest.FromString,
        )


class TodoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddUser(self, request, context):
    """Add a user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteUser(self, request, context):
    """Delete a user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddTodo(self, request, context):
    """Add, Get, Delete and Set Todo as Complete
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetToDo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetDoneToDo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteToDo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetToDos(self, request, context):
    """Get or Delete list of Todos
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteToDos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddUser': grpc.unary_unary_rpc_method_handler(
          servicer.AddUser,
          request_deserializer=todo__pb2.User.FromString,
          response_serializer=todo__pb2.UserRequest.SerializeToString,
      ),
      'DeleteUser': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteUser,
          request_deserializer=todo__pb2.UserRequest.FromString,
          response_serializer=todo__pb2.UserRequest.SerializeToString,
      ),
      'AddTodo': grpc.unary_unary_rpc_method_handler(
          servicer.AddTodo,
          request_deserializer=todo__pb2.ToDo.FromString,
          response_serializer=todo__pb2.ToDoRequest.SerializeToString,
      ),
      'GetToDo': grpc.unary_unary_rpc_method_handler(
          servicer.GetToDo,
          request_deserializer=todo__pb2.ToDoRequest.FromString,
          response_serializer=todo__pb2.ToDo.SerializeToString,
      ),
      'SetDoneToDo': grpc.unary_unary_rpc_method_handler(
          servicer.SetDoneToDo,
          request_deserializer=todo__pb2.ToDoRequest.FromString,
          response_serializer=todo__pb2.ToDoRequest.SerializeToString,
      ),
      'DeleteToDo': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteToDo,
          request_deserializer=todo__pb2.ToDoRequest.FromString,
          response_serializer=todo__pb2.ToDoRequest.SerializeToString,
      ),
      'GetToDos': grpc.unary_stream_rpc_method_handler(
          servicer.GetToDos,
          request_deserializer=todo__pb2.UserRequest.FromString,
          response_serializer=todo__pb2.ToDo.SerializeToString,
      ),
      'DeleteToDos': grpc.unary_stream_rpc_method_handler(
          servicer.DeleteToDos,
          request_deserializer=todo__pb2.UserRequest.FromString,
          response_serializer=todo__pb2.ToDoRequest.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protobuf.TodoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
