# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protobuf.todo_pb2 as todo__pb2


class TodoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddUser = channel.unary_unary(
        '/protobuf.TodoService/AddUser',
        request_serializer=todo__pb2.User.SerializeToString,
        response_deserializer=todo__pb2.User.FromString,
        )
    self.AddToDo = channel.unary_unary(
        '/protobuf.TodoService/AddToDo',
        request_serializer=todo__pb2.ToDo.SerializeToString,
        response_deserializer=todo__pb2.ToDo.FromString,
        )
    self.UpdateToDo = channel.unary_unary(
        '/protobuf.TodoService/UpdateToDo',
        request_serializer=todo__pb2.ToDo.SerializeToString,
        response_deserializer=todo__pb2.ToDo.FromString,
        )
    self.GetToDoList = channel.unary_stream(
        '/protobuf.TodoService/GetToDoList',
        request_serializer=todo__pb2.User.SerializeToString,
        response_deserializer=todo__pb2.ToDo.FromString,
        )


class TodoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddUser(self, request, context):
    """Add a user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddToDo(self, request, context):
    """Add, update ToDo
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateToDo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetToDoList(self, request, context):
    """Get or Delete list of ToDo
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddUser': grpc.unary_unary_rpc_method_handler(
          servicer.AddUser,
          request_deserializer=todo__pb2.User.FromString,
          response_serializer=todo__pb2.User.SerializeToString,
      ),
      'AddToDo': grpc.unary_unary_rpc_method_handler(
          servicer.AddToDo,
          request_deserializer=todo__pb2.ToDo.FromString,
          response_serializer=todo__pb2.ToDo.SerializeToString,
      ),
      'UpdateToDo': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateToDo,
          request_deserializer=todo__pb2.ToDo.FromString,
          response_serializer=todo__pb2.ToDo.SerializeToString,
      ),
      'GetToDoList': grpc.unary_stream_rpc_method_handler(
          servicer.GetToDoList,
          request_deserializer=todo__pb2.User.FromString,
          response_serializer=todo__pb2.ToDo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protobuf.TodoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
