# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protobuf.todo_pb2 as todo__pb2


class TodoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.add_user = channel.unary_unary(
        '/protobuf.TodoService/add_user',
        request_serializer=todo__pb2.User.SerializeToString,
        response_deserializer=todo__pb2.User.FromString,
        )
    self.add_todo = channel.unary_unary(
        '/protobuf.TodoService/add_todo',
        request_serializer=todo__pb2.ToDo.SerializeToString,
        response_deserializer=todo__pb2.ToDo.FromString,
        )
    self.update_todo = channel.unary_unary(
        '/protobuf.TodoService/update_todo',
        request_serializer=todo__pb2.ToDo.SerializeToString,
        response_deserializer=todo__pb2.ToDo.FromString,
        )
    self.get_todo_list = channel.unary_stream(
        '/protobuf.TodoService/get_todo_list',
        request_serializer=todo__pb2.User.SerializeToString,
        response_deserializer=todo__pb2.ToDo.FromString,
        )
    self.delete_todo_list = channel.unary_stream(
        '/protobuf.TodoService/delete_todo_list',
        request_serializer=todo__pb2.User.SerializeToString,
        response_deserializer=todo__pb2.ToDo.FromString,
        )


class TodoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def add_user(self, request, context):
    """Add a user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def add_todo(self, request, context):
    """Add, update ToDo
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update_todo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_todo_list(self, request, context):
    """Get or Delete list of Todos
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete_todo_list(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'add_user': grpc.unary_unary_rpc_method_handler(
          servicer.add_user,
          request_deserializer=todo__pb2.User.FromString,
          response_serializer=todo__pb2.User.SerializeToString,
      ),
      'add_todo': grpc.unary_unary_rpc_method_handler(
          servicer.add_todo,
          request_deserializer=todo__pb2.ToDo.FromString,
          response_serializer=todo__pb2.ToDo.SerializeToString,
      ),
      'update_todo': grpc.unary_unary_rpc_method_handler(
          servicer.update_todo,
          request_deserializer=todo__pb2.ToDo.FromString,
          response_serializer=todo__pb2.ToDo.SerializeToString,
      ),
      'get_todo_list': grpc.unary_stream_rpc_method_handler(
          servicer.get_todo_list,
          request_deserializer=todo__pb2.User.FromString,
          response_serializer=todo__pb2.ToDo.SerializeToString,
      ),
      'delete_todo_list': grpc.unary_stream_rpc_method_handler(
          servicer.delete_todo_list,
          request_deserializer=todo__pb2.User.FromString,
          response_serializer=todo__pb2.ToDo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protobuf.TodoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
