WELCOME_MESSAGE = 'Welcome to Todo application '
ENTER_NAME = 'Hi, Please enter name to continue: '
ENTER_TODO_NO = 'Enter todo number: '
ENTER_OPTION = 'Enter your option: '
SEPARATOR = '#-----------------------------------------------------------#'
SEPARATOR_COMPLETED = '#---------------------- Completed --------------------------#'
EMPTY_TODO_LIST = 'No ToDo\'s found!'
CHOICES = ' 1 -> Add    2 -> mark as done   3 -> delete todo    4-> Exit'

ERROR_FAIL = 'Error, Something happened!'
ERROR_TODO = 'Enter a todo: '
ERROR_FAILED_ADD_TODO = 'Failed to add todo!'
ERROR_WRONG_CHOICE = 'Wrong choice, Try again!'
ERROR_FAILED_TO_MARK_TODO = 'Failed to mark todo:{0} as done'
ERROR_FAILED_DELETE_TODO = 'Failed to delete todo:{0}'
